### ISSUE TITLE
Ending slash is removed from long URLs and the uncached test is redirected to the /?nowprocket version

### ISSUE THREAD

**Issue by WordPresseur** [alfonso100/rocket-hangar#12]
Example: https://wphangar.com/lab/psi-test.php?url=https%3A%2F%2Fartclassesmalta.com%2Fcourse-category%2Fexperiences%2F

**Comment by alfonso100** [comment]
this is our first issue! 🥇 
 thank you @WordPresseur for this report. 
I will take a look at this one

**Comment by alfonso100** [comment]
Removed the manipulation of trailing slashes with https://github.com/alfonso100/rocket-hangar/commit/d66ba5ed6c8011da703770d0997ee7ab0f722db9

the URL tested will be passed without modification to Pagespeed
