### ISSUE TITLE
"Keep requests count low" is pre-checked unnecessarily

### ISSUE THREAD

**Issue by webtrainingwheels** [alfonso100/rocket-hangar#14]
For example: https://wphangar.com/lab/psi-test.php?url=https%3A%2F%2Fthemovieculture.com%2F
https://jmp.sh/d5ckhl4

The request count is 23 and total size 512KB, I don't think requests or size are an issue here.

I believe this audit shows up on every pagespeed test, its presence doesn't mean something is wrong. 
I think it's only informational and not a warning. We may even consider removing it from our tool. 

When the page size is too large, the "avoid enormous network payloads" message will be triggered anyway.

What do you think?

**Comment by sandyfigueroa** [comment]
You are right @webtrainingwheels! This audit shows up on every pagespeed test.

Google has its own criteria for displaying its results. I am working on a way to not check irrelevant audits / results.

**Comment by sandyfigueroa** [comment]
Fixed in commit https://github.com/alfonso100/rocket-hangar/commit/b10e01f661dedc363391b701f137e2d3b2288ab4 😊
