### ISSUE TITLE
Don't recommend RUCSS and OCD together

### ISSUE THREAD

**Issue by webtrainingwheels** [alfonso100/rocket-hangar#15]
Hello! 
Since we now know that we should use only RUCSS by itself and not at the same time as OCD, and with 3.10 coming, is there a way to prevent this result?
https://jmp.sh/K4XZWce
🙏

**Comment by alfonso100** [comment]
thanks Lucy. I've merged both options accordingly to 3.10 like this: https://jmp.sh/Rv6Qlqt
this single recommendation will be present only if RUCSS and Async CSS are disabled
